### ISSUE TITLE
Model mesh URI tag being generated incorrectly?

### ISSUE THREAD

**Issue by kouroshgz** [FirefoxMetzger/python-sdformat#2]
Hello,

Im running into an issue with trying to generate a model with a mesh field, and I cant tell if I'm using the syntax incorrectly or if there is simply an issue with generating mesh tags. 
Below is my code

`
 element = SDF(

                    Model(
                        Link(name="link1"),
                        Visual(
                           Geometry(
                            Geometry.Mesh(
                                uri = mesh_uri
                                )
                           ),
                            name = "visual",
                        ),
                        Plugin(
                            name = "pose_plugin",
                            filename = "libpose_plugin.so"
                        ),
                        name=obj.name,
                    ),
                    version="1.5",
                )
`

And here is the sdf that is generated

`<sdf version="1.5">
  <model name="scenicAdhocSphere">
    <link name="link1"/>
    <visual name="visual">
      <geometry>
        <mesh uri="/mnt/c/Users/Kourosh/Desktop/3dscenic/Scenic-devel/src/scenic/simulators/gazebo/meshes/scenic_6546/simulation_1/scenicAdhocSphere_iteration_1/scenicAdhocSphere.dae"/>
      </geometry>
    </visual>
    <plugin name="pose_plugin" filename="libpose_plugin.so"/>
  </model>
</sdf>
`

According to the gazebo docs (https://classic.gazebosim.org/tutorials?tut=import_mesh&cat=build_robot), the following is what a mesh field is meant to look like:

`
<visual name="visual">
  <pose>0 0 0 1.5708 0 0</pose>
  <geometry>
    <mesh><uri>file://duck.dae</uri></mesh>
  </geometry>
</visual>
`
As you can see, the uri section of the example is its own tag, while in the one I've generated, it is merely a field.  

I believe this is why when I try to generate a model in gazebo based off an SDF i've generated, they are invisible. 

I'd appreciate any help with this, thanks!

**Comment by FirefoxMetzger** [comment]
You are almost there:

- models don't have a `visual` property. Rather it's the `Link` (see the [spec](http://sdformat.org/spec?ver=1.5&elem=link#link_visual))
- Since the URI is an element and not an attribute you need to use its constructor (`Geometry.Mesh.Uri`).
- to set the text of an XML / SDF element, you can use the `text` attribute

Putting it together:

```python
from pysdf import *

element = SDF(
    Model(
        Link(
            Visual(
                Geometry(Geometry.Mesh(Geometry.Mesh.Uri(text="something"))),
                name="visual",
            ),
            name="link1"
        ),
        Plugin(name="pose_plugin", filename="libpose_plugin.so"),
        name="hello_world",
    ),
    version="1.5",
)

print(element.to_xml(pretty_print=True))
```
```
<sdf version="1.5">
  <model name="hello_world">
    <link name="link1">
      <visual name="visual">
        <geometry>
          <mesh>
            <uri>something</uri>
          </mesh>
        </geometry>
      </visual>
    </link>
    <plugin name="pose_plugin" filename="libpose_plugin.so"/>
  </model>
</sdf>
```

**Comment by kouroshgz** [comment]
Thank you so much for the great explanation, absolute life saver!
